# ==========================
# chat_gen.py — Generate HTML Chat History for EduMentor
# ==========================

import io
from datetime import datetime
import markdown2  # make sure 'markdown2' is installed: pip install markdown2

def generate_html(messages):
    """
    Converts the chat messages into a styled HTML format
    that can be downloaded as a readable chat history.
    """

    if not messages:
        return "<html><body><h3>No chat history available.</h3></body></html>"

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    chat_content = ""
    interaction_count = 0

    # Emojis / labels for clarity
    user_label = "🧑‍🎓 User"
    assistant_label = "👨🏻‍🏫 AI-Tutor"

    # Loop through chat messages
    for message in messages:
        role_class = 'user' if message['role'] == 'user' else 'assistant'
        label = user_label if role_class == 'user' else assistant_label

        if role_class == 'user':
            interaction_count += 1

        # Safely convert markdown to HTML
        formatted_content = markdown2.markdown(message['content']).replace('\\n', '<br>')
        chat_content += f"""
        <div class='message {role_class}'>
            <span class='label'>{label}:</span>
            <div class='text'>{formatted_content}</div>
        </div>
        """

    # Combine everything into a nice HTML structure
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>EduMentor Chat History</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <style>
            body {{
                background-color: #f5f5f5;
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            }}
            .container {{
                margin-top: 30px;
                background: white;
                border-radius: 10px;
                box-shadow: 0 4px 10px rgba(0,0,0,.1);
                padding: 20px;
            }}
            .header {{
                background-color: #2d6a4f;
                color: white;
                padding: 1rem;
                text-align: center;
                border-radius: 10px 10px 0 0;
            }}
            .message {{
                padding: 0.8rem 1rem;
                margin: 10px 0;
                border-radius: 10px;
                font-size: 1rem;
                line-height: 1.5;
            }}
            .user {{
                background-color: #e8f5e9;
                border-left: 5px solid #2d6a4f;
            }}
            .assistant {{
                background-color: #f1f8e9;
                border-left: 5px solid #74c69d;
            }}
            .label {{
                font-weight: bold;
                display: block;
                margin-bottom: 5px;
            }}
            .footer {{
                background-color: #2d6a4f;
                color: white;
                text-align: center;
                padding: 1rem;
                border-radius: 0 0 10px 10px;
                margin-top: 20px;
            }}
            .meta {{
                font-size: 0.9rem;
                color: #6c757d;
                text-align: center;
                margin-bottom: 1rem;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h2>EduMentor Chat History</h2>
            </div>
            <div class="meta">
                Generated on: {timestamp} <br>
                Total Q&A Interactions: {interaction_count}
            </div>
            <div>{chat_content}</div>
            <div class="footer">
                This conversation was generated by <strong>EduMentor AI Tutor</strong>.
            </div>
        </div>
    </body>
    </html>
    """

    return html_content
